module.exports = {
    SAVE_CURRENCY_DATA : "SAVE_CURRENCY_DATA",
    CURRENCY_LIST: "CURRENCY_LIST",
    ADD_CURRENCY:"ADD_CURRENCY",
    REMOVE_CURRENCY:"REMOVE_CURRENCY",
    SAVE_CURRENT_INPUT:"SAVE_CURRENT_INPUT"
}